nayduck ci

diff --git a/.github/workflows/nightly_nayduck.yml b/.github/workflows/nightly_nayduck.yml
--- a/.github/workflows/nightly_nayduck.yml
+++ b/.github/workflows/nightly_nayduck.yml
@@ -1,21 +1,41 @@
-name: Nightly Nayduck tests check
+name: CI Nayduck tests
 on:
   merge_group:
+  
+  workflow_dispatch:
 
 jobs:
-  nightly_nayduck_tests:
+  nayduck_tests:
     runs-on: "ubuntu-latest"
-    timeout-minutes: 10
+    timeout-minutes: 60
 
     steps:
       - name: Install JQ json processor
         run: sudo apt install jq
       
-      # In this step we get the latest nightly results from the nayduck server
-      # and check if there are any non-passing tests
-      - name: Check if there are any non-passing tests
+      - name: Install required python modules
         run: |
-          NIGHTLY_RESULTS=$(curl -s https://nayduck.nearone.org/api/nightly-events)
-          UNSUCCESSFUL_TESTS=$(jq -e '.tests | .[][] | select(.[2] != "PASSED" ) ' <<< ${NIGHTLY_RESULTS} )
-          if [ -z "$UNSUCCESSFUL_TESTS" ] ; then echo "Nightly Nayduck tests OK"; \
-          else echo "Nightly Nayduck tests are failing" && exit 1; fi
+          pip3 install -r pytest/requirements.txt
+
+      - name: Run Nayduck tests and wait for results
+        run: |
+          NEW_TEST=$(python3 scripts/nayduck.py  --test-file nightly/ci.txt)
+          RUN_ID=$(echo $NEW_TEST | grep https | sed -E 's|.*\/run\/([0-9]+)|\1|g')
+
+          # wait all the tests to finish
+          while true; do
+            TEST_RESULTS=$(curl -s https://nayduck.nearone.org/api/run/$RUN_ID)
+            TESTS_NOT_READY=$( jq -e '.tests | .[] | select(.status == "RUNNING" or .status == "PENDING" ) ' <<< ${TEST_RESULTS} )
+            if [ -z "$TESTS_NOT_READY" ]; then break; fi
+            sleep 15
+          done
+
+          UNSUCCESSFUL_TESTS=$(jq -e '.tests | .[] | select(.status != "PASSED" ) ' <<< ${TEST_RESULTS} )
+          if [ -z "$UNSUCCESSFUL_TESTS" ]; then
+            echo "Nayduck CI tests passed."
+            echo "Results available at https://nayduck.nearone.org/#/run/$RUN_ID"
+          else
+            echo "CI Nayduck tests are failing https://nayduck.nearone.org/#/run/$RUN_ID."
+            echo "Fix them before merging"
+            exit 1
+          fi
